#content for nav.html
title: "GGG: Giorgio · Genova · Glasgow."
subtitle: "Giorgio Ciacchella's personal blog"
logo_img: "/assets/logo/favicon.png"
baseurl: ""
google_tracking_id: # Google Analytics Tracking ID: UA-XXXXXXXX-X
copyright_name: Giorgio Ciacchella

# GitHub Pages
lsi: false
safe: true
source: ""
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

# SEO data (https://github.com/jekyll/jekyll-seo-tag)
logo: "/assets/logo/favicon.ico"
description: Giorgio Ciacchella
author:
  name: Giorgio Ciacchella
  email: ciakki.g@gmail.com

social:
  name: Giorgio Ciacchella
  links:
    - https://github.com/ciakkig

# Build settings
permalink: pretty
paginate: 12

defaults:
    scope:
      path: "assets/img/"
    values:
      image: true

plugins:
- jekyll-paginate
- jekyll-feed
- jekyll-sitemap
- jekyll-seo-tag

include:
- _pages

exclude:
- Gemfile
- Gemfile.lock
- package.json
- .vendor
- README.md
- LICENSE.md